services:
  Nours\RestAdminBundle\Menu\Voter\ResourceRouteVoter:
    arguments: [ '@request_stack' ]
    tags:
        - { name: knp_menu.voter }

  Nours\RestAdminBundle\Menu\Helper\ResourceMenuHelper:
    arguments: [ '@Nours\RestAdminBundle\AdminManager' ]