services:
  rest_admin.param_fetcher.orm:
    class: Nours\RestAdminBundle\ParamFetcher\DoctrineParamFetcher
    arguments: [ '@doctrine.orm.entity_manager' ]

  rest_admin.listener.orm:
    class: Nours\RestAdminBundle\EventListener\DoctrineListener
    arguments: [ '@rest_admin.param_fetcher.orm' ]
    tags: [ { name: 'kernel.event_subscriber' }]
