services:
  Nours\RestAdminBundle\ParamFetcher\DoctrineParamFetcher:
    arguments: [ '@doctrine.orm.entity_manager' ]
    tags: [ { name: rest_admin.param_fetcher, alias: orm }]

  Nours\RestAdminBundle\Handler\ORMHandler:
    public: true
    arguments: [ '@doctrine.orm.entity_manager' ]

  Nours\RestAdminBundle\EventListener\ORMActionConfigListener:
    tags: [ { name: kernel.event_subscriber }]
