services:
  rest_admin.param_fetcher.orm:
    class: Nours\RestAdminBundle\ParamFetcher\DoctrineParamFetcher
    arguments: [ '@doctrine.orm.entity_manager' ]

  rest_admin.handler.orm:
    class: Nours\RestAdminBundle\Handler\ORMHandler
    arguments: [ '@doctrine.orm.entity_manager' ]


  rest_admin.orm_param_fetcher:
    class: Nours\RestAdminBundle\EventListener\DoctrineParamFetcherListener
    arguments: [ '@rest_admin.param_fetcher.orm' ]
    tags: [ { name: 'kernel.event_subscriber' }]


  rest_admin.listener.orm_action_config:
    class: Nours\RestAdminBundle\EventListener\ORMActionConfigListener
    arguments: [ '@doctrine.orm.entity_manager' ]
    tags: [ { name: 'kernel.event_subscriber' }]
