services:
##############################
# Command
##############################
  Nours\RestAdminBundle\Command\ResourcesDebugCommand:
    arguments: [ '@Nours\RestAdminBundle\AdminManager' ]
    tags: [ { name: console.command }]

##############################
# Controller
##############################
  Nours\RestAdminBundle\Controller\IndexController:
    arguments:
      - '@doctrine.orm.entity_manager'
    tags: ['controller.service_arguments']

  Nours\RestAdminBundle\Controller\FormController:
    arguments:
      - '@Nours\RestAdminBundle\Domain\ResourceDataFactory'
      - '@Nours\RestAdminBundle\Form\ActionFormFactory'
      - '@Nours\RestAdminBundle\Form\FormSuccessHandler'
    tags: ['controller.service_arguments']

##############################
# Resources loading
##############################
  Nours\RestAdminBundle\Loader\YamlResourceLoader:
    arguments: [ '@file_locator', '@Nours\RestAdminBundle\Loader\ResourceFactory' ]
    tags: [ { name: rest_admin.loader }]

  Nours\RestAdminBundle\Loader\AnnotationFileLoader:
    arguments: [ '@file_locator', '@Nours\RestAdminBundle\Loader\AnnotationClassLoader' ]
    tags: [ { name: rest_admin.loader }]

  Nours\RestAdminBundle\Loader\AnnotationDirectoryLoader:
    arguments: [ '@file_locator', '@Nours\RestAdminBundle\Loader\AnnotationFileLoader' ]
    tags: [ { name: rest_admin.loader }]

  Nours\RestAdminBundle\Loader\AnnotationClassLoader:
    arguments: [ '@annotation_reader', '@Nours\RestAdminBundle\Loader\ResourceFactory' ]
#    tags: [ { name: rest_admin.loader }]

  rest_admin.loader_resolver:
    class: Symfony\Component\Config\Loader\LoaderResolver

  rest_admin.loader:
    class: Symfony\Component\Config\Loader\DelegatingLoader
#    public: true      # Tests only
    arguments: [ '@rest_admin.loader_resolver' ]

  Nours\RestAdminBundle\Loader\ResourceFactory:
#    public: true      # Tests only
    arguments: [ '@Nours\RestAdminBundle\ActionManager', '@event_dispatcher', '%rest_admin.resource_class%' ]

##############################
# Routing
##############################
  Nours\RestAdminBundle\Routing\RoutingLoader:
    arguments: [ '@Nours\RestAdminBundle\AdminManager', '@Nours\RestAdminBundle\ActionManager', '@event_dispatcher' ]
    tags: [ { name: 'routing.loader' } ]

##############################
# Core
##############################
  Nours\RestAdminBundle\AdminManager:
    class: Nours\RestAdminBundle\AdminManager
    public: true
    arguments: [ '@rest_admin.loader', '%rest_admin.resource%', '%kernel.cache_dir%', '%kernel.debug%' ]
    tags: [ { name: 'kernel.cache_warmer' } ]

  Nours\RestAdminBundle\ActionManager:
    public: true

  Nours\RestAdminBundle\View\ViewHandler:
    arguments: [ '@rest_admin.loader', '%rest_admin.resource%' ]

  Nours\RestAdminBundle\Domain\ResourceDataFactory:
    public: true
    arguments:
     - '@controller_resolver'
     - '@argument_resolver'

  Nours\RestAdminBundle\Handler\RedirectHandler:
    public: true
    arguments: [ '@Nours\RestAdminBundle\Helper\AdminHelper' ]

  Nours\RestAdminBundle\Handler\CopyFactory:
    public: true

##############################
# Helper
##############################
  Nours\RestAdminBundle\Helper\AdminHelper:
    class: Nours\RestAdminBundle\Helper\AdminHelper
    public: true
    arguments: [ '@request_stack', '@Nours\RestAdminBundle\AdminManager', '@router' ]

##############################
# Core actions
##############################
  Nours\RestAdminBundle\Action\Core\CustomActionBuilder:
    arguments: [ '%rest_admin.actions.custom%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  Nours\RestAdminBundle\Action\Core\IndexActionBuilder:
    arguments: [ '%rest_admin.actions.index%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  Nours\RestAdminBundle\Action\Core\GetActionBuilder:
    arguments: [ '%rest_admin.actions.get%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  Nours\RestAdminBundle\Action\Core\CreateActionBuilder:
    arguments: [ '%rest_admin.actions.create%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  Nours\RestAdminBundle\Action\Core\EditActionBuilder:
    arguments: [ '%rest_admin.actions.edit%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  Nours\RestAdminBundle\Action\Core\CopyActionBuilder:
    arguments: [ '%rest_admin.actions.copy%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  Nours\RestAdminBundle\Action\Core\DeleteActionBuilder:
    arguments: [ '%rest_admin.actions.delete%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  Nours\RestAdminBundle\Action\Core\BulkDeleteActionBuilder:
    arguments: [ '%rest_admin.actions.bulk_delete%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  Nours\RestAdminBundle\Action\Core\FormActionBuilder:
    arguments: [ '%rest_admin.actions.form%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

##############################
# Forms
##############################
  Nours\RestAdminBundle\Form\ActionFormFactory:
    public: true
    arguments:
     - '@Nours\RestAdminBundle\ActionManager'
     - '@form.factory'
     - '@router'
     - '@event_dispatcher'

  Nours\RestAdminBundle\Form\FormSuccessHandler:
    public: true
    arguments:
     - '@controller_resolver'
     - '@argument_resolver'

##############################
# Param fetcher
##############################
  Nours\RestAdminBundle\ParamFetcher\CustomParamFetcher:
    arguments:
     - '@controller_resolver'
     - '@argument_resolver'
    tags: [ { name: rest_admin.param_fetcher, alias: custom }]

##############################
# Event listeners
##############################
  Nours\RestAdminBundle\EventListener\RequestListener:
    arguments: [ '@Nours\RestAdminBundle\AdminManager' ]
    tags: [ { name: 'kernel.event_subscriber' }]

  Nours\RestAdminBundle\EventListener\RedirectActionConfigListener:
    tags: [ { name: 'kernel.event_subscriber' }]

  Nours\RestAdminBundle\EventListener\ParamFetcherListener:
    arguments:
      - '@service_container'
      - []  # To be replaced in Compiler/ParamFetcherPass
      - '%rest_admin.default_param_fetcher%'
    tags: [ { name: 'kernel.event_subscriber' }]