services:
##############################
# Resources loading
##############################
  rest_admin.loader.yml:
    class: Nours\RestAdminBundle\Loader\YamlResourceLoader
    public: false
    arguments: [ '@file_locator', '@rest_admin.loader.resource_factory' ]
    tags: [ { name: rest_admin.loader }]

  rest_admin.loader.annotation_file:
    class: Nours\RestAdminBundle\Loader\AnnotationFileLoader
    public: false
    arguments: [ '@file_locator', '@rest_admin.loader.annotation_class' ]
    tags: [ { name: rest_admin.loader }]

  rest_admin.loader.annotation_directory:
    class: Nours\RestAdminBundle\Loader\AnnotationDirectoryLoader
    public: false
    arguments: [ '@file_locator', '@rest_admin.loader.annotation_file' ]
    tags: [ { name: rest_admin.loader }]

  rest_admin.loader.annotation_class:
    class: Nours\RestAdminBundle\Loader\AnnotationClassLoader
    public: false
    arguments: [ '@annotation_reader', '@rest_admin.loader.resource_factory' ]
#    tags: [ { name: rest_admin.loader }]

  rest_admin.loader_resolver:
    class: Symfony\Component\Config\Loader\LoaderResolver
    public: false

  rest_admin.loader:
    class: Symfony\Component\Config\Loader\DelegatingLoader
    arguments: [ '@rest_admin.loader_resolver' ]

  rest_admin.loader.resource_factory:
    class: Nours\RestAdminBundle\Loader\ResourceFactory
    arguments: [ '@rest_admin.action_manager', '@event_dispatcher', '%rest_admin.resource_class%' ]

##############################
# Routing
##############################
  rest_admin.routing_loader:
    class: Nours\RestAdminBundle\Routing\RoutingLoader
    arguments: [ '@rest_admin.manager', '@rest_admin.action_manager', '@event_dispatcher' ]
    tags: [ { name: 'routing.loader' } ]

  rest_admin.routing.url_generator:
    class: Nours\RestAdminBundle\Routing\UrlGenerator
    arguments: [ '@router' ]

##############################
# Core
##############################
  rest_admin.manager:
    class: Nours\RestAdminBundle\AdminManager
    arguments: [ '@rest_admin.loader', '%rest_admin.resource%', '%kernel.cache_dir%', '%kernel.debug%' ]
    tags: [ { name: 'kernel.cache_warmer' } ]

  rest_admin.action_manager:
    class: Nours\RestAdminBundle\ActionManager

  rest_admin.view_handler:
    class: Nours\RestAdminBundle\View\ViewHandler
    arguments: [ '@rest_admin.loader', '%rest_admin.resource%' ]

  rest_admin.data_factory:
    class: Nours\RestAdminBundle\Domain\ResourceDataFactory
    arguments: [ '@controller_resolver' ]

#  rest_admin.resource_handler:
#    class: Nours\RestAdminBundle\Domain\ResourceHandler
#    arguments: [ '@controller_resolver' ]

  rest_admin.handler.redirect:
    class: Nours\RestAdminBundle\Handler\RedirectHandler
    arguments: [ '@router' ]

##############################
# Core actions
##############################
  rest_admin.action_builder.default:
    class: Nours\RestAdminBundle\Action\Core\DefaultActionBuilder
    arguments: [ '%rest_admin.actions.default%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  rest_admin.action_builder.index:
    class: Nours\RestAdminBundle\Action\Core\IndexActionBuilder
    arguments: [ '%rest_admin.actions.index%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  rest_admin.action_builder.get:
    class: Nours\RestAdminBundle\Action\Core\GetActionBuilder
    arguments: [ '%rest_admin.actions.get%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  rest_admin.action_builder.create:
    class: Nours\RestAdminBundle\Action\Core\CreateActionBuilder
    arguments: [ '%rest_admin.actions.create%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  rest_admin.action_builder.edit:
    class: Nours\RestAdminBundle\Action\Core\EditActionBuilder
    arguments: [ '%rest_admin.actions.edit%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  rest_admin.action_builder.delete:
    class: Nours\RestAdminBundle\Action\Core\DeleteActionBuilder
    arguments: [ '%rest_admin.actions.delete%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  rest_admin.action_builder.bulk_delete:
    class: Nours\RestAdminBundle\Action\Core\BulkDeleteActionBuilder
    arguments: [ '%rest_admin.actions.bulk_delete%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  rest_admin.action_builder.form:
    class: Nours\RestAdminBundle\Action\Core\FormActionBuilder
    arguments: [ '%rest_admin.actions.form%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

##############################
# Forms
##############################
  rest_admin.action_form_factory:
    class: Nours\RestAdminBundle\Form\ActionFormFactory
    arguments: [ '@rest_admin.action_manager', '@form.factory', '@router' ]

  rest_admin.form_success_handler:
    class: Nours\RestAdminBundle\Form\FormSuccessHandler
    arguments: [ '@controller_resolver' ]

  rest_admin.form_type.delete:
    class: Nours\RestAdminBundle\Form\Type\DeleteType
    tags: [ { name: 'form.type', alias: 'rest_admin_delete' } ]

  rest_admin.form_type.bulk_delete:
    class: Nours\RestAdminBundle\Form\Type\BulkDeleteType
    tags: [ { name: 'form.type', alias: 'rest_admin_bulk_delete' } ]


##############################
# Param fetcher
##############################
  rest_admin.param_fetcher.custom:
    class: Nours\RestAdminBundle\ParamFetcher\CustomParamFetcher
    arguments: [ '@controller_resolver' ]
    tags: [ { name: rest_admin.param_fetcher, alias: custom }]

##############################
# Event listeners
##############################
  rest_admin.listener.request:
    class: Nours\RestAdminBundle\EventListener\RequestListener
    arguments: [ '@rest_admin.manager' ]
    tags: [ { name: 'kernel.event_subscriber' }]

  rest_admin.listener.redirect_action_config:
    class: Nours\RestAdminBundle\EventListener\RedirectActionConfigListener
#    arguments: [ '@rest_admin.manager' ]
    tags: [ { name: 'kernel.event_subscriber' }]

  rest_admin.listener.param_fetcher:
    class: Nours\RestAdminBundle\EventListener\ParamFetcherListener
    arguments:
      - '@service_container'
      - []  # To be replaced in Compiler/ParamFetcherPass
      - '%rest_admin.default_param_fetcher%'
    tags: [ { name: 'kernel.event_subscriber' }]