services:
##############################
# Resources loading
##############################
  rest_admin.loader.yml:
    class: Nours\RestAdminBundle\Loader\YamlResourceLoader
    public: false
    arguments: [ '@file_locator', '@rest_admin.action_factory' ]
    tags: [ { name: rest_admin.loader }]

  rest_admin.loader.annotation_file:
    class: Nours\RestAdminBundle\Loader\AnnotationFileLoader
    public: false
    arguments: [ '@file_locator', '@rest_admin.loader.annotation_class' ]
    tags: [ { name: rest_admin.loader }]

  rest_admin.loader.annotation_directory:
    class: Nours\RestAdminBundle\Loader\AnnotationDirectoryLoader
    public: false
    arguments: [ '@file_locator', '@rest_admin.loader.annotation_file' ]
    tags: [ { name: rest_admin.loader }]

  rest_admin.loader.annotation_class:
    class: Nours\RestAdminBundle\Loader\AnnotationClassLoader
    public: false
    arguments: [ '@annotation_reader', '@rest_admin.action_factory' ]
#    tags: [ { name: rest_admin.loader }]

  rest_admin.loader_resolver:
    class: Symfony\Component\Config\Loader\LoaderResolver
    public: false

  rest_admin.loader:
    class: Symfony\Component\Config\Loader\DelegatingLoader
    arguments: [ '@rest_admin.loader_resolver' ]

  rest_admin.action_factory:
    class: Nours\RestAdminBundle\Loader\ActionFactory
    arguments: [ '@rest_admin.action_manager' ]

##############################
# Core classes
##############################
  rest_admin.manager:
    class: Nours\RestAdminBundle\AdminManager
    arguments: [ '@rest_admin.loader', '%rest_admin.resource%' ]

  rest_admin.action_manager:
    class: Nours\RestAdminBundle\ActionManager

  rest_admin.core_controller:
    class: Nours\RestAdminBundle\Controller\CoreController
    arguments: [ '@rest_admin.manager', '@rest_admin.event_dispatcher', '@rest_admin.action_form_factory' ]

  rest_admin.routing_loader:
    class: Nours\RestAdminBundle\Routing\RoutingLoader
    arguments: [ '@rest_admin.manager', '@rest_admin.action_manager' ]
    tags: [ { name: 'routing.loader' } ]

  rest_admin.event_dispatcher:
    class: Nours\RestAdminBundle\Api\ApiEventDispatcher
    arguments: [ '@rest_admin.manager', '@rest_admin.action_manager' ]

##############################
# Core actions
##############################
  rest_admin.action_builder.index:
    class: Nours\RestAdminBundle\Action\Core\IndexActionBuilder
    arguments: [ '%rest_admin.templates.index%', '%rest_admin.controllers.index%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  rest_admin.action_builder.get:
    class: Nours\RestAdminBundle\Action\Core\GetActionBuilder
    arguments: [ '%rest_admin.templates.get%', '%rest_admin.controllers.get%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  rest_admin.action_builder.create:
    class: Nours\RestAdminBundle\Action\Core\CreateActionBuilder
    arguments: [ '%rest_admin.templates.create%', '%rest_admin.controllers.create%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  rest_admin.action_builder.edit:
    class: Nours\RestAdminBundle\Action\Core\EditActionBuilder
    arguments: [ '%rest_admin.templates.edit%', '%rest_admin.controllers.edit%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

  rest_admin.action_builder.delete:
    class: Nours\RestAdminBundle\Action\Core\DeleteActionBuilder
    arguments: [ '%rest_admin.templates.delete%', '%rest_admin.controllers.delete%' ]
    tags: [ { name: 'rest_admin.action_builder' } ]

##############################
# Forms
##############################
  rest_admin.action_form_factory:
    class: Nours\RestAdminBundle\Action\ActionFormFactory
    arguments: [ '@rest_admin.action_manager', '@form.factory', '@router' ]

##############################
# Events
##############################
  rest_admin.view_renderer_subscriber:
    class: Nours\RestAdminBundle\EventListener\RendererSubscriber
    arguments: [ '@twig' ]
    tags: [ { name: 'rest_admin.event_subscriber' }]

  rest_admin.json_renderer_subscriber:
    class: Nours\RestAdminBundle\EventListener\JsonSubscriber
    arguments: [ '@jms_serializer.serializer' ]
    tags: [ { name: 'rest_admin.event_subscriber' }]


  rest_admin.listener.request:
    class: Nours\RestAdminBundle\EventListener\RequestListener
    arguments: [ '@rest_admin.manager' ]
    tags: [ { name: 'kernel.event_subscriber' }]

  rest_admin.listener.doctrine:
    class: Nours\RestAdminBundle\EventListener\DoctrineListener
    arguments: [ '@doctrine' ]
    tags: [ { name: 'kernel.event_subscriber' }]