services:
  Nours\RestAdminBundle\Table\Extension\AdminExtension:
    arguments: [ '@Nours\RestAdminBundle\Helper\AdminHelper', '%rest_admin.table.disable_child_filter%' ]
    tags: [ { name: nours_table.extension } ]

  Nours\RestAdminBundle\Table\Field\AdminActionsType:
    arguments: [ '@Nours\RestAdminBundle\Helper\AdminHelper' ]
    tags: [ { name: nours_table.field_type } ]