services:
  rest_admin.twig.extension:
    class: Nours\RestAdminBundle\Twig\Extension\RestAdminExtension
    arguments:
      - '@rest_admin.helper'
      - '%rest_admin.template.action%'
    tags: [ { name: 'twig.extension' }]
