services:
  Nours\RestAdminBundle\Twig\Extension\RestAdminExtension:
    arguments:
      - '@Nours\RestAdminBundle\Helper\AdminHelper'
      - '%rest_admin.template.action%'
    tags: [ { name: 'twig.extension' }]
