services:
  Nours\RestAdminBundle\View\DelegatingHandler:

  Nours\RestAdminBundle\View\TwigHandler:
    arguments: [ '@twig', '%rest_admin.listeners.templating.formats%' ]
    tags: [ { name: 'rest_admin.view_handler' } ]

  Nours\RestAdminBundle\View\JsonHandler:
    arguments: [ '@rest_admin.serializer' ]
    tags: [ { name: 'rest_admin.view_handler' } ]

  Nours\RestAdminBundle\EventListener\ViewListener:
    arguments: [ '@Nours\RestAdminBundle\View\DelegatingHandler' ]
    tags: [ { name: 'kernel.event_subscriber' }]