dist: trusty
sudo: required
language: php

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=3.4.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 5.6
      env: SYMFONY_VERSION='3.3.*'
    - php: 5.6
      env: SYMFONY_VERSION='3.4.*'
    - php: 7.1
      env: SYMFONY_VERSION='2.8.*'
    - php: 7.1
      env: SYMFONY_VERSION='3.3.*'
    - php: 7.1
      env: SYMFONY_VERSION='3.4.*'
    - php: 7.1
      env: SYMFONY_VERSION='4.*'

install:
  - phpenv config-add travis.php.ini
  - php -ini | grep memory_limit

before_script:
  - composer require "symfony/symfony:${SYMFONY_VERSION}" --dev
  - vendor/bin/phpunit --version

script: vendor/bin/phpunit